version: 0.5.{build}
branches:
  only:
  - dev-gh
  - master
  - release
image: Visual Studio 2019
clone_depth: 1
before_build:
- cmd: >-
    git clone --depth 1 --single-branch --branch %APPVEYOR_REPO_BRANCH% https://github.com/DataExperts/dexih.transforms ../dexih.transforms
    git clone --depth 1 --single-branch --branch %APPVEYOR_REPO_BRANCH% https://github.com/DataExperts/Dexih.App.Operations ../Dexih.App.Operations
    dotnet restore
build:
  project: dexih.remote.sln
  verbosity: minimal
after_build:
- cmd: >-
  
artifacts:
- path: dexih*.zip


  for:

# The release branch publishes without the version suffix, making an official release.
-
  branches:
    only:
      - release

  configuration: Release
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_NUMBER% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/dotnet
  - 7z a dexih.remote.%APPVEYOR_BUILD_VERSION%-%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%/dotnet

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% -r win7-x64 --version-suffix %APPVEYOR_BUILD_NUMBER% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/win7-64
  - 7z a dexih.remote.windows_%APPVEYOR_BUILD_VERSION%-%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%/win7-64

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% -r osx-x64 --version-suffix %APPVEYOR_BUILD_NUMBER% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/osx-x64
  - 7z a dexih.remote.osx_%APPVEYOR_BUILD_VERSION%-%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%/osx-x64

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% -r linux-x64 --version-suffix %APPVEYOR_BUILD_NUMBER% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/linux-x64
  - 7z a dexih.remote.linux_%APPVEYOR_BUILD_VERSION%-%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%/linux-x64

deploy:
- provider: GitHub
  release: dexih-remote-v$(appveyor_build_version)
  auth_token:
    secure: lEaZ/om1UTRS6Xa947/5WxZVbBW6A+ZHmPu7aXRRDqkjX1+LYTfh9xL1CueonyuC
  artifact: /.*\.zip/
  prerelease: false

# master and dev branchs runs test only, no publishing packages
-
  branches:
    only:
      - master
      - /dev-.*/

  configuration: Debug
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% --version-suffix %APPVEYOR_BUILD_NUMBER% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/dotnet
  - 7z a dexih.remote.%APPVEYOR_BUILD_VERSION%-%APPVEYOR_BUILD_NUMBER%.zip %APPVEYOR_BUILD_FOLDER%/dotnet

deploy:
- provider: GitHub
  release: dexih-remote-v$(appveyor_build_version)
  auth_token:
    secure: lEaZ/om1UTRS6Xa947/5WxZVbBW6A+ZHmPu7aXRRDqkjX1+LYTfh9xL1CueonyuC
  artifact: /.*\.zip/
  prerelease: true
  