version: 0.5.{build}
branches:
  only:
  - dev-gh
  - master
  - release
image: Visual Studio 2019
configuration:
- Debug
- Release
init:
 - ps: $Env:LABEL = "CI" +$Env:APPVEYOR_BUILD_NUMBER.PadLeft(5, "0")
clone_depth: 1
before_build:
  - git clone --depth 1 --single-branch --branch %APPVEYOR_REPO_BRANCH% https://github.com/DataExperts/dexih.transforms ../dexih.transforms
  - git clone --depth 1 --single-branch --branch %APPVEYOR_REPO_BRANCH% https://github.com/DataExperts/Dexih.App.Operations ../Dexih.App.Operations
  - dotnet restore

artifacts:
- path: dexih*.zip

deploy:
- provider: GitHub
  release: dexih-remote-v$(appveyor_build_version)
  auth_token:
    secure: lEaZ/om1UTRS6Xa947/5WxZVbBW6A+ZHmPu7aXRRDqkjX1+LYTfh9xL1CueonyuC
  artifact: /.*\.zip/
  prerelease: true
   on: 
    branch: 
     - master
     - release

  for:

# The release branch publishes without the version suffix, making an official release.
-
  branches:
    only:
      - release

  configuration: Release
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% --version-suffix %LABEL% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/dotnet
  - 7z a dexih.remote.%APPVEYOR_BUILD_VERSION%-%LABEL%.zip %APPVEYOR_BUILD_FOLDER%/dotnet

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% -r win7-x64 --version-suffix %LABEL% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/win7-64
  - 7z a dexih.remote.windows_%APPVEYOR_BUILD_VERSION%-%LABEL%.zip %APPVEYOR_BUILD_FOLDER%/win7-64

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% -r osx-x64 --version-suffix %LABEL% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/osx-x64
  - 7z a dexih.remote.osx_%APPVEYOR_BUILD_VERSION%-%LABEL%.zip %APPVEYOR_BUILD_FOLDER%/osx-x64

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% -r linux-x64 --version-suffix %LABEL% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/linux-x64
  - 7z a dexih.remote.linux_%APPVEYOR_BUILD_VERSION%-%LABEL%.zip %APPVEYOR_BUILD_FOLDER%/linux-x64

# master and dev branch/dev publishes with prerelease:true
-
  branches:
    only:
      - master
      - /dev-.*/

  configuration: Debug
  build_script:
  - appveyor-retry dotnet restore -v Minimal
  - dotnet build -c %CONFIGURATION%

  - dotnet publish src/dexih.remote/dexih.remote.csproj -c %CONFIGURATION% --version-suffix %LABEL% -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -o %APPVEYOR_BUILD_FOLDER%/dotnet
  - 7z a dexih.remote.%APPVEYOR_BUILD_VERSION%-%LABEL%.zip %APPVEYOR_BUILD_FOLDER%/dotnet

  